import {
  WEATHER_API_KEY,
  BASE_WEATHER_URL,
  OPENCAGEDATA_API_KEY,
  BASE_OPENCAGEDATA_URL,
} from "@env";

export default {
  WEATHER_API_KEY,
  BASE_WEATHER_URL,
  OPENCAGEDATA_API_KEY,
  BASE_OPENCAGEDATA_URL,
};
